version: 2
jobs:
  build:
    branches:
      only: master
    docker:
      -image:circleci/node:7.10
    steps:
      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: test
          command: echo "no test"

      - run:
          name: build
          command: npm run build
